'use client';

import Image from 'next/image';
import { useEffect, useState } from 'react';

const phoneDisplay = '021 370 9914';
const phoneLink = 'tel:+27213709914';
const directionsLink = 'https://www.google.com/maps/search/?api=1&query=Pacific+Road+House+Jakes+Gerwel+Drive+Cape+Town';
const slides = [
  { number: '01', name: 'Gatsby', kicker: 'Loaded / messy / serious hunger', copy: 'A big Cape Town mood, built for the stop.', image: '/food/hero-gatsby.png', tone: 'orange' },
  { number: '02', name: 'Hake & chips', kicker: 'Crisp / hot / straight from the counter', copy: 'A Roadhouse classic in the visual language of heat.', image: '/food/food-study-hake-chips-v1.png', tone: 'blue' },
  { number: '03', name: 'Steak sandwich', kicker: 'Toasted / generous / direct', copy: 'Comfort between two slices. No speech required.', image: '/food/food-study-steak-sandwich-v1.png', tone: 'gold' },
  { number: '04', name: 'Chicken', kicker: 'Golden / filling / worth the pull-in', copy: 'One more reason to make the cafeteria your next stop.', image: '/food/food-study-chicken-v1.png', tone: 'cream' },
];

export default function Home() {
  const [active, setActive] = useState(0);
  const [paused, setPaused] = useState(false);
  const slide = slides[active];
  useEffect(() => { if (paused) return; const timer = window.setInterval(() => setActive((current) => (current + 1) % slides.length), 5600); return () => window.clearInterval(timer); }, [paused]);
  const changeSlide = (direction: number) => setActive((current) => (current + direction + slides.length) % slides.length);
  return <main>
    <div className="utility-bar"><p>Pacific Business Park · Jakes Gerwel Drive · Cape Town</p><a href={phoneLink}>Call {phoneDisplay}</a></div>
    <header className="site-header"><a className="brand" href="#top" aria-label="Pacific Roadhouse home"><Image src="/brand/wordmark.svg" alt="Pacific Roadhouse" width={1800} height={650} priority /></a><nav aria-label="Main navigation"><a href="#food">Food</a><a href="#visit">Find us</a></nav><a className="button button-small button-orange" href={phoneLink}>Call the shop <span aria-hidden="true">↗</span></a></header>
    <section className="slideshow-hero" id="top"><div className="hero-grid" aria-hidden="true" /><div className="hero-copy"><p className="eyebrow light">A proper Cape Town cafeteria</p><h1>Big food.<span>Good energy.</span></h1><p className="hero-intro">Roadhouse favourites, done properly. Come hungry, call ahead, and make the stop worth it.</p><div className="hero-actions"><a className="button button-orange" href="#food">Enter the food story <span aria-hidden="true">↓</span></a><a className="button button-ghost" href={directionsLink} target="_blank" rel="noreferrer">Find us <span aria-hidden="true">↗</span></a></div><p className="microcopy">Walk in or call · no online ordering</p></div><div className="hero-orbit" aria-hidden="true"><span>Pacific Roadhouse</span><span>Come hungry</span><span>01 / 04</span></div></section>
    <section className={`food-showcase tone-${slide.tone}`} id="food" aria-label="Pacific Roadhouse food showcase" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)}><div className="showcase-top"><div><p className="eyebrow">The cafeteria section</p><h2>Pick your<br /><em>hunger.</em></h2></div><p className="showcase-note">A moving picture of Roadhouse appetite. Visual studies only — call the shop for today&apos;s menu, prices and availability.</p></div><div className="slide-stage" aria-live="polite"><div className="slide-copy"><span className="slide-number">{slide.number} / 04</span><p className="slide-kicker">{slide.kicker}</p><h3>{slide.name}</h3><p className="slide-description">{slide.copy}</p><a className="button button-navy" href={phoneLink}>Call for today&apos;s menu <span aria-hidden="true">↗</span></a></div><div className="slide-image-wrap"><Image key={slide.image} src={slide.image} alt={`Concept study of ${slide.name}`} fill sizes="(max-width: 780px) 92vw, 60vw" priority={active === 0} /><span className="slide-sticker">Concept study<br />Confirm at the counter</span></div></div><div className="showcase-controls"><div className="slide-dots" role="tablist" aria-label="Choose food slide">{slides.map((item, index) => <button key={item.number} className={index === active ? 'is-active' : ''} role="tab" aria-selected={index === active} aria-label={`Show ${item.name}`} onClick={() => setActive(index)}><span>{item.number}</span><i /></button>)}</div><div className="control-buttons"><button onClick={() => changeSlide(-1)} aria-label="Previous slide">←</button><button onClick={() => setPaused((value) => !value)} aria-label={paused ? 'Play slideshow' : 'Pause slideshow'}>{paused ? 'Play' : 'Pause'}</button><button onClick={() => changeSlide(1)} aria-label="Next slide">→</button></div></div></section>
    <section className="visit section" id="visit"><div className="visit-intro"><p className="eyebrow">Find the counter</p><h2>Come hungry.</h2><p>Pacific Roadhouse is at Pacific Business Park on Jakes Gerwel Drive. Walk in, or call to confirm today&apos;s menu and closing time.</p></div><div className="visit-panel"><div className="visit-detail"><span>Address</span><p>Pacific Business Park<br />Jakes Gerwel Drive<br />Cape Town, 7750</p></div><div className="visit-detail"><span>Telephone</span><a href={phoneLink}>{phoneDisplay}</a></div><div className="visit-actions"><a className="button button-orange" href={phoneLink}>Call now <span aria-hidden="true">↗</span></a><a className="button button-navy" href={directionsLink} target="_blank" rel="noreferrer">Open in Maps <span aria-hidden="true">↗</span></a></div></div></section>
    <footer><Image src="/brand/wordmark.svg" alt="Pacific Roadhouse" width={1800} height={650} /><p>Big flavour. Fair value. No fuss.</p><a href="#top">Back to top ↑</a><div className="axiel-signature"><span>Website system by</span><a href="https://axiel.co.za/" aria-label="Website system by AXIEL, built on ATLAS OS">AXIEL / ATLAS OS</a></div></footer><div className="mobile-dock"><a href="#food">Food</a><a href={directionsLink} target="_blank" rel="noreferrer">Directions</a><a href={phoneLink}>Call</a></div>
  </main>;
}
